# Generated by Django 4.0.1 on 2022-06-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editorders',
            table='orderform',
        ),
    ]
