# Generated by Django 4.0.1 on 2022-05-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_product_image_product_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='articleimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='media/productimage/'),
            preserve_default=False,
        ),
    ]
