# Generated by Django 4.0.1 on 2022-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_editorders_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorders',
            name='customer',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='editorders',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='editorders',
            name='productname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
