# Generated by Django 4.0.1 on 2022-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_signupasseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
