# Generated by Django 4.0.1 on 2022-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupasseller',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupasseller',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupasseller',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
