# Generated by Django 4.0 on 2022-07-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_signupasseller_address_signupasseller_username_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='ProductForm',
        ),
    ]
