# Generated by Django 4.0.1 on 2022-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_product_gender_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
