# Generated by Django 4.0.1 on 2022-07-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_product_table'),
        ('Home', '0013_alter_product_category'),
    ]

    operations = [
    ]
