# Generated by Django 4.0 on 2022-07-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_merge_20220705_2109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
