# Generated by Django 4.0.1 on 2022-07-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_merge_20220704_2249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
