<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-07-04 17:04
=======
# Generated by Django 4.0 on 2022-07-05 15:24
>>>>>>> a1358a9f3b8595d8bd77ba65888a8908f4293bb1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Home', '0014_merge_20220704_2249'),
=======
        ('Home', '0014_merge_20220705_2109'),
>>>>>>> a1358a9f3b8595d8bd77ba65888a8908f4293bb1
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
