# Generated by Django 4.0 on 2022-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=200)),
                ('c_email', models.CharField(max_length=200)),
                ('c_message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
